[project]
name = "calculator-gui"
version = "0.1.0"
description = "simple calculator starter project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
    "ttkthemes>=3.2.2",
]
